// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvrtbmgrkrrmuhckfjlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2cnRibWdya3JybXVoY2tmamx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NzQwNzcsImV4cCI6MjA1OTA1MDA3N30.pHrICeSylCCXt7INoI5-3VOJ4zQIWdnQVM3_UZulqxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);