// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlgvttkzgmqhczvyjcwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZ3Z0dGt6Z21xaGN6dnlqY3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTUyNjYsImV4cCI6MjA2NDY3MTI2Nn0.1e7XJBMcuz4lHkVI3Yp6OXmGzvSZ01N5Zx_zplgHcqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);